os: linux
dist: xenial
language: generic
install:
  - |
    if [[ ! -f /usr/bin/hugo ]]; then
      wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Linux-64bit.tar.gz
      sudo tar -xzf hugo_0.58.3_Linux-64bit.tar.gz -C /usr/bin/
    fi
script:
  - hugo

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: public
    on:
       branch: master    
      
